spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=task_manager
spring.datasource.username=sa
spring.datasource.password=Password123@
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.SQLServer2012Dialect